name: advent-of-code
version: 0.3.0.0
synopsis: Advent of Code 2018
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/aoc18
verbatim:
  cabal-version: 2.0
extra-source-files:
- ChangeLog.md
dependencies:
- base ^>=4.11
- bytestring ^>=0.10.8
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  exposed-modules:
  - Day01
  - Day02
  - Day03
  - Util
  dependencies:
  - hashable ^>= 1.2
  - unordered-containers ^>= 0.2.9
  - trifecta >=2
_executable: &exe
  ghc-options:
  - -O2
  source-dirs: app
  dependencies:
  - advent-of-code
executables:
  day01:
    <<: *exe
    main: day01/Main.hs
  day02:
    <<: *exe
    main: day02/Main.hs
  day03:
    <<: *exe
    main: day03/Main.hs
