name: aoc
version: !include "./VERSION"
synopsis: My Haskell solutions to Advent of Code problems
author: Eric Bailey
maintainer: eric@ericb.me
license-file: LICENSE
license: MIT
github: yurrriq/aoc19
extra-source-files:
- CHANGELOG.md
- LICENSE
- README.md
- input/day*.txt
dependencies:
- base
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  exposed-modules:
  - Data.AOC19.Day02
  - Data.AOC19.Day03
  - Data.AOC19.Day04
  - Data.AOC19.Day05
  - Data.AOC19.Day06
  - Data.AOC19.Day07
  - Data.AOC19.Day08
  - Data.AOC19.Day09
  - Data.AOC19.Day12
  dependencies:
  - composition
  - conduit
  - data-ordlist
  - digits
  - hashable
  - mtl
  - lens
  - transformers
  - trifecta
  - unordered-containers
  - vector
# executable:
#   ghc-options:
#   - -O2
#   source-dirs: app
#   main: Main.hs
#   dependencies:
#   - aoc
tests:
  aoc-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - aoc
    - conduit
    - digits
    - tasty
    - tasty-discover
    - tasty-hunit
    - vector
