name: aoc
version: !include "./VERSION"
synopsis: My Haskell solutions to Advent of Code problems
author: Eric Bailey
maintainer: eric@ericb.me
license-file: LICENSE
license: MIT
github: yurrriq/aoc19
extra-source-files:
- CHANGELOG.md
- LICENSE
- README.md
- VERSION
data-files: input/day*.txt
dependencies:
- base
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  dependencies:
  - composition
  - conduit
  - data-ordlist
  - digits
  - hashable
  - mtl
  - lens
  - linear
  - transformers
  - trifecta
  - unordered-containers
  - vector
tests:
  aoc-test:
    main: Main.hs
    ghc-options:
    - -O0
    - -threaded
    source-dirs: test
    dependencies:
    - aoc
    - conduit
    - digits
    - tasty
    - tasty-discover
    - tasty-hunit
    - vector
