name: advent-of-code
version: !include "./VERSION"
synopsis: My Haskell solutions to Advent of Code problems
author: Eric Bailey
maintainer: eric@ericb.me
license-file: LICENSE
license: MIT
github: yurrriq/advent-of-code
extra-source-files:
- LICENSE
- VERSION
data-files:
- input/*/day*.txt
dependencies:
- base
- bytestring
- hashable
- parsers
- split
- template-haskell
- trifecta
- unordered-containers
default-extensions:
- TemplateHaskell
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  dependencies:
  - composition
  - conduit
  - containers
  - cryptonite
  - data-ordlist
  - dlist
  - fast-digits
  - finite-typelits
  - free-algebras
  - groups
  - hashable
  - hashable
  - lens
  - linear
  - mtl
  - transformers
  - unordered-containers
  - vector
_executable: &executable
  ghc-options:
  - -O0
  - -threaded
  other-modules:
  - AdventOfCode.Input
  - AdventOfCode.TH
  - AdventOfCode.Util
  - Paths_advent_of_code
  source-dirs: src
executables:
  aoc-2015-day06:
    <<: *executable
    main: AdventOfCode.Year2015.Day06
    other-modules:
    - AdventOfCode.Input
    - AdventOfCode.TH
    - AdventOfCode.Util
    - AdventOfCode.Year2015.Day06.Parsers
    - AdventOfCode.Year2015.Day06.Types
    - Paths_advent_of_code
    dependencies:
    - containers
    - linear
    - transformers
  aoc-2015-day10:
    <<: *executable
    main: AdventOfCode.Year2015.Day10
    other-modules: []
  aoc-2015-day11:
    <<: *executable
    main: AdventOfCode.Year2015.Day11
    other-modules: []
  aoc-2016-day05:
    <<: *executable
    main: AdventOfCode.Year2016.Day05
    dependencies:
    - containers
    - cryptonite
  aoc-2018-day01:
    <<: *executable
    main: AdventOfCode.Year2018.Day01
  aoc-2018-day02:
    <<: *executable
    main: AdventOfCode.Year2018.Day02
  aoc-2018-day03:
    <<: *executable
    main: AdventOfCode.Year2018.Day03
  aoc-2018-day04:
    <<: *executable
    main: AdventOfCode.Year2018.Day04
  aoc-2018-day05:
    <<: *executable
    main: AdventOfCode.Year2018.Day05
    dependencies:
    - finite-typelits
    - free-algebras
    - groups
  aoc-2019-day02:
    <<: *executable
    main: AdventOfCode.Year2019.Day02
    dependencies:
    - vector
  aoc-2019-day03:
    <<: *executable
    main: AdventOfCode.Year2019.Day03
  aoc-2019-day04:
    <<: *executable
    main: AdventOfCode.Year2019.Day04
    dependencies:
    - data-ordlist
    - fast-digits
  aoc-2019-day05:
    <<: *executable
    main: AdventOfCode.Year2019.Day05
    dependencies:
    - fast-digits
    - mtl
    - vector
  aoc-2019-day06:
    <<: *executable
    main: AdventOfCode.Year2019.Day06
  aoc-2019-day07:
    <<: *executable
    main: AdventOfCode.Year2019.Day07
    dependencies:
    - conduit
    - fast-digits
    - mtl
    - transformers
    - vector
  aoc-2019-day08:
    <<: *executable
    main: AdventOfCode.Year2019.Day08
  aoc-2019-day09:
    <<: *executable
    main: AdventOfCode.Year2019.Day09
    dependencies:
    - conduit
    - fast-digits
    - mtl
    - transformers
    - vector
  aoc-2019-day10:
    <<: *executable
    main: AdventOfCode.Year2019.Day10
  aoc-2019-day12:
    <<: *executable
    main: AdventOfCode.Year2019.Day12
    dependencies:
    - linear
  aoc-2020-day01:
    <<: *executable
    main: AdventOfCode.Year2020.Day01
    dependencies:
    - groups
  aoc-2020-day02:
    <<: *executable
    main: AdventOfCode.Year2020.Day02
  aoc-2020-day03:
    <<: *executable
    main: AdventOfCode.Year2020.Day03
    dependencies:
    - vector
  aoc-2020-day05:
    <<: *executable
    main: AdventOfCode.Year2020.Day05
    dependencies:
    - fast-digits
  aoc-2020-day06:
    <<: *executable
    main: AdventOfCode.Year2020.Day06
_benchmark: &benchmark
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O2
  source-dirs: bench
  dependencies:
    - advent-of-code
    - criterion
benchmarks:
  aoc-2020-day03-bench:
    <<: *benchmark
    main: Bench.hs
    source-dirs: bench/AdventOfCode/Year2020/Day03
tests:
  advent-of-code-test:
    main: Main.hs
    ghc-options:
    - -O0
    - -threaded
    source-dirs: test
    dependencies:
    - advent-of-code
    - conduit
    - fast-digits
    - tasty
    - tasty-discover
    - tasty-hunit
    - vector
